### ISSUE TITLE
Column example naming does not follow "Python - Gettings started"-guide

### ISSUE THREAD

**Issue by qlik-des** [qlik-oss/server-side-extension#36]
In the guide "Getting started with python" the example says to use e.g.
SSEPlugin=columnsupport,localhost:50053

Although when opening  SSE_Column_Operations.qvf file the columnsupport is named Column and the app does not work as expected without changing this.

**Expected**
Homogeneous naming either columnsupport  or Column in all places.

**Comment by josefinestal** [comment]
Hi @qlik-des ! 
Thank you for reaching out! Unfortunately, I can't find the issue you are describing. Is it on master you saw this? 

Alternatively, you might have mixed up the `examplename` and the `EngineName` (see [this section](https://github.com/qlik-oss/server-side-extension/blob/master/examples/python/GetStarted.md#running-the-python-examples)). The former is the name of the python package and the latter is the plugin name you are using when configuring the plugin and hence the name you are using in the app. 

Kind regards, 
Josefine

**Comment by qlik-des** [comment]
You are correct I've mixed up examplename with Enginename. Sorry about that,  I'll close the issue

**Comment by josefinestal** [comment]
No worries! I'm glad I could help.
